apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx-on-k8s
  name: nginx-on-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-on-k8s
  template:
    metadata:
      labels:
        app: nginx-on-k8s
    spec:
      containers:
        - image: klzsysy/nginx-on-k8s:1.13.12
          imagePullPolicy: Always
          name: nginx-on-k8s
          ports:
            - containerPort: 8080
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-on-k8s
  name: nginx-on-k8s
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: nginx-on-k8s
  type: ClusterIP