kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: reader-endpoints-role
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: read-endpoints
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: reader-endpoints-role
  apiGroup: rbac.authorization.k8s.io
  